### ISSUE TITLE
The kid and x5t values need swapped. See https://datatracker.ietf.org/doc/html/rfc7517

### ISSUE THREAD

**Issue by steveoshima** [ConsumerDataRight/mock-register#13]
**Describe the bug**
Noticed a major bug in around the JWKS generation. The kid and x5t values need swapped.
SSA JWTs have the incorrecct kid values. They are using the x5t value.

**To Reproduce**
1. See endpoint response for /cdr-register/v1/jwks
2. See endpoint response for /cdr-register/v1/banking/data-recipients/brands/F3F0C40B-9DF8-491A-AF1D-81CB9AB5F021/software-products/6F7A1B8E-8799-48A8-9011-E3920391F713/ssa

**Expected behaviour**
kid values and x5t values to follow standards defined in 
https://datatracker.ietf.org/doc/html/rfc7517
https://datatracker.ietf.org/doc/html/rfc7638

**Additional context**
Example of values that need swapped
"kid": "AA24F185EE3F67504808FC4E26B135B99E63BDA9",
 "x5t": "qiTxhe4_Z1BICPxOJrE1uZ5jvak",

Can we get an ETA on the fix please?
Thanks for the repo.

**Comment by ACCC-DF** [comment]
Hi @steveoshima 

Thanks getting involved and for taking the time to raise this issue.

Are you able to provide some further clarification?

From what I am seeing, the SSA JWKS endpoint (`/cdr-register/v1/jwks`) returns the following:

```
{
    "keys": [
        {
            "alg": "PS256",
            "e": "AQAB",
            "key_ops": [
                "sign",
                "verify"
            ],
            "kid": "542A9B91600488088CD4D816916A9F4488DD2651",
            "kty": "RSA",
            "n": "0qE0TxxopsXaRNZ7qr9w0Sy0-kBGabAjB5BDn0ekvevomMFCvxdxw2d95aLc09k59cFH_dNsP0DCCE9ALp5Ob8gXNHcKEnKzFeLnZGo0xDSw6Xu-JuBw5-Z9bDfSWG_iSoPitG4Bk9j1S2brsKkOOa8iIE0JqkFMu___0ifoaA0C62c5QJIH8qvEr7x-zG9H9Bt1aFOznMy-TvI2s91otg4N_E1RKfRHnwPRjuw7fO1UCxn2LRLR0J_vz_uEHBs9CjH7KcPknPw43nmL-JDWQjUgM2FioTXDwhBEb5o_FQkLJlZmVrxg27iyAePYnoWDenGQsSS_2AhBAfZjqTIXBQ"
        }
    ]
}
```

Where kid is `542A9B91600488088CD4D816916A9F4488DD2651`.

When retrieving an SSA for a software product (`/cdr-register/v1/banking/data-recipients/brands/F3F0C40B-9DF8-491A-AF1D-81CB9AB5F021/software-products/6F7A1B8E-8799-48A8-9011-E3920391F713/ssa`) the following is returned:

```
eyJhbGciOiJQUzI1NiIsImtpZCI6IjU0MkE5QjkxNjAwNDg4MDg4Q0Q0RDgxNjkxNkE5RjQ0ODhERDI2NTEiLCJ0eXAiOiJKV1QifQ.ew0KICAicmVjaXBpZW50X2Jhc2VfdXJpIjogImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcCIsDQogICJsZWdhbF9lbnRpdHlfaWQiOiAiZGU4MTVhOTMtODViMy00ZmU4LTk1MTMtMzNhZDhmNDM1OWQwIiwNCiAgImxlZ2FsX2VudGl0eV9uYW1lIjogInlveW8gU29mdHdhcmUgQ29tcGFueSIsDQogICJpc3MiOiAiY2RyLXJlZ2lzdGVyIiwNCiAgImlhdCI6IDE2MjQ5MjM2MTgsDQogICJleHAiOiAxNjI0OTI0MjE4LA0KICAianRpIjogIjU1MjkzODBlYmYxYzRiZmNiYTIyODA5MGM3ODc5MzEzIiwNCiAgIm9yZ19pZCI6ICJmM2YwYzQwYi05ZGY4LTQ5MWEtYWYxZC04MWNiOWFiNWYwMjEiLA0KICAib3JnX25hbWUiOiAiWW9ZbyIsDQogICJjbGllbnRfbmFtZSI6ICJNeUJ1ZGdldEhlbHBlciIsDQogICJjbGllbnRfZGVzY3JpcHRpb24iOiAiQSBwcm9kdWN0IHRvIGhlbHAgeW91IG1hbmFnZSB5b3VyIGJ1ZGdldCIsDQogICJjbGllbnRfdXJpIjogImh0dHBzOi8veW95b3NvZnR3YXJlL215YnVkZ2V0YXBwIiwNCiAgInJlZGlyZWN0X3VyaXMiOiBbDQogICAgImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9jYWxsYmFjayIsDQogICAgImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9yZXR1cm4iDQogIF0sDQogICJsb2dvX3VyaSI6ICJodHRwczovL3lveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9pbWcvbG9nby5wbmciLA0KICAidG9zX3VyaSI6ICJodHRwczovL3lveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC90ZXJtcyIsDQogICJwb2xpY3lfdXJpIjogImh0dHBzOi8veW95b3NvZnR3YXJlL215YnVkZ2V0YXBwL3BvbGljeSIsDQogICJqd2tzX3VyaSI6ICJodHRwczovL2xvY2FsaG9zdDo3MDA2L2xvb3BiYWNrL01vY2tEYXRhUmVjaXBpZW50SndrcyIsDQogICJyZXZvY2F0aW9uX3VyaSI6ICJodHRwczovL2FwaS55b3lvc29mdHdhcmUvbXlidWRnZXRhcHAvcmV2b2tlIiwNCiAgInNvZnR3YXJlX2lkIjogIjZmN2ExYjhlLTg3OTktNDhhOC05MDExLWUzOTIwMzkxZjcxMyIsDQogICJzb2Z0d2FyZV9yb2xlcyI6ICJkYXRhLXJlY2lwaWVudC1zb2Z0d2FyZS1wcm9kdWN0IiwNCiAgInNjb3BlIjogIm9wZW5pZCBwcm9maWxlIGJhbms6YWNjb3VudHMuYmFzaWM6cmVhZCBiYW5rOmFjY291bnRzLmRldGFpbDpyZWFkIGJhbms6dHJhbnNhY3Rpb25zOnJlYWQgYmFuazpwYXllZXM6cmVhZCBiYW5rOnJlZ3VsYXJfcGF5bWVudHM6cmVhZCBjb21tb246Y3VzdG9tZXIuYmFzaWM6cmVhZCBjb21tb246Y3VzdG9tZXIuZGV0YWlsOnJlYWQgY2RyOnJlZ2lzdHJhdGlvbiINCn0.ujF6T-13BEq3aFlScBD-V-VEEx09taB4gxTAD8UGELsQRiWRUj7aJqmywBl2vX2xlg3Vooa8crxvbZs6DrNojKMZ8Ar8I7IpYbZ-KCAErYOr0RamivfKCPjM6azFTCMuksNzku7StxjWk6W9dU4rw3pQz99xN-KxPNn3_Ux8uKyDrz4DVvp8i3rEuNc0cSenCNqjSUfpX9K250tOA7b1HKRK6wpNSeR3J2SX02X4DHW_MEZXrKup8bX0XhqXvk0Np8UmCzNEQsCf7Kj-oRZ0-lnNUnKZb-Cb7JNKZ15juL1jT-gslzkzKfdHxb3mQZZBTI17F4-OvtW6TvdMyV3Y9w
```

Which when decoded has the following header:

```
{
  "alg": "PS256",
  "kid": "542A9B91600488088CD4D816916A9F4488DD2651",
  "typ": "JWT"
}
```

Where the `kid` matches the `kid` in the SSA JWKS endpoint.

The values mentioned in the issue raised relate to the OIDC jwks endpoint (`/idp/.well-known/openid-configuration/jwks`) which is used for access token validation.

```
{
    "keys": [
        {
            "kty": "RSA",
            "use": "sig",
            "kid": "AA24F185EE3F67504808FC4E26B135B99E63BDA9",
            "x5t": "qiTxhe4_Z1BICPxOJrE1uZ5jvak",
            ...
```

Are you able to confirm the issue raised and provide any further information that may help diagnose?

**Comment by steveoshima** [comment]
The kid and x5t values are incorrect.

x5t is a base64url-encoded SHA-1 thumbprint (a.k.a. digest) of the DER encoding of an X.509 certificate.

kid is defined by using values "e", "kty", "n" from the JWK, maintain lexicographic order of "e","kty","n" then based64url-encode this using SHA-1. Please see  https://datatracker.ietf.org/doc/html/rfc7638#section-3.1. 
Recommend you use the same sha size as the live CDR register. Is this sha1 or sha256?

The x5t values you have are actually kid values and the kid values you have are actually the x5t values.
Please swap them around.

Thanks.

**Comment by kenoby-dev** [comment]
The production CDR JWKS endpoint is located at: [https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks](https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks)

As you can see from that endpoint, the Mock Register JWKS endpoint (https://localhost:7000/idp/.well-known/openid-configuration/jwks) follows the same format and structure.

## Production JWKS:

```
{
  "keys": [
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "847DAC3EE8DD0B32CCB6C1130847D59F3FE7C513",
      "x5t": "hH2sPujdCzLMtsETCEfVnz_nxRM",
      "e": "AQAB",
      "n": "0Vty7vzhv2HQMUzGshSCSuk9VmyxC9OgTiEnqVo7J6-PpTIOrVm9RDhraMzIzMfxb-G4OAahnVGTNEqAHGM2LCbL5K8n8z5g0wgbedqnFJvnwdFiko7juZx351qgN_ZKRHu4wk6BdtgjTmZGFyyxswuiXVGiiJGO5hxv9aFDeMdxg0Z9mOYxO2OV8Bf982PCr8chE_X6bgpu-LrMnJ2005uiwX1q1z4ywiB83Wrx_ALVc3Ul-jlCAmnfi5o88DQmtO8QuXjcLHpR8LRDqJG-S6ufK4nd-8qjyxPDEMIF8fsaJbUyhSK_uxq6ms9z_Udpx3Pgxdh1qk4Ch1eCZ7NqZw",
      "x5c": [
        "MIIGCjCCBPKgAwIBAgIQHX+3zSIj553nQ068uClg6TANBgkqhkiG9w0BAQsFADCBijELMAkGA1UEBhMCQVUxNzA1BgNVBAoTLkF1c3RyYWxpYW4gQ29tcGV0aXRpb24gYW5kIENvbnN1bWVyIENvbW1pc3Npb24xHDAaBgNVBAsTE0NvbnN1bWVyIERhdGEgUmlnaHQxJDAiBgNVBAMTG0NEUiBCYW5raW5nIEludGVybWVkaWF0ZSBDQTAeFw0yMDAzMjMwMDAwMDBaFw0yMjAzMjMyMzU5NTlaMH0xHDAaBgNVBAsME0NvbnN1bWVyIERhdGEgUmlnaHQxNzA1BgNVBAoMLkF1c3RyYWxpYW4gQ29tcGV0aXRpb24gYW5kIENvbnN1bWVyIENvbW1pc3Npb24xJDAiBgNVBAMMG2lkcC5jZHItcmVnaXN0ZXIuY2RyLmdvdi5hdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANFbcu784b9h0DFMxrIUgkrpPVZssQvToE4hJ6laOyevj6UyDq1ZvUQ4a2jMyMzH8W/huDgGoZ1RkzRKgBxjNiwmy+SvJ/M+YNMIG3napxSb58HRYpKO47mcd+daoDf2SkR7uMJOgXbYI05mRhcssbMLol1RooiRjuYcb/WhQ3jHcYNGfZjmMTtjlfAX/fNjwq/HIRP1+m4Kbvi6zJydtNObosF9atc+MsIgfN1q8fwC1XN1Jfo5QgJp34uaPPA0JrTvELl43Cx6UfC0Q6iRvkurnyuJ3fvKo8sTwxDCBfH7GiW1MoUiv7sauprPc/1Hacdz4MXYdapOAodXgmezamcCAwEAAaOCAnYwggJyMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBSholmEtpJq7erdQV38KQoKSSpjSTAuBgpghkgBhvhFARADBCAwHgYTYIZIAYb4RQEQAQMBBAGDp/WiOhYHMTE0MDU5MTA5BgpghkgBhvhFARAFBCswKQIBABYkYUhSMGNITTZMeTl3YTJrdGNtRXVjM2x0WVhWMGFDNWpiMjA9MIH4BgNVHSAEgfAwge0wgeoGBiokAYMQATCB3zAoBggrBgEFBQcCARYcaHR0cHM6Ly9DRFIuZ292LmF1L3Jlc291cmNlczCBsgYIKwYBBQUHAgIwgaUagaJJc3N1ZWQgdW5kZXIgdGhlIEF1c3RyYWxpYW4gQ29tcGV0aXRpb24gJiBDb25zdW1lciBDb21taXNzaW9uIChBQ0NDKSBDb25zdW1lciBEYXRhIFJpZ2h0IChDRFIpIFBLSSBDUC4gUmVmZXIgdG8gaHR0cHM6Ly9DRFIuZ292LmF1L3Jlc291cmNlcyBmb3IgbW9yZSBpbmZvcm1hdGlvbi4wXQYDVR0fBFYwVDBSoFCgToZMaHR0cDovL3BraS1jcmwuc3ltYXV0aC5jb20vY2FfZjg1ZDA2Yjc1ODJlYWExOGQ5Mjk3OWJmYTMzODI0NzQvTGF0ZXN0Q1JMLmNybDA4BggrBgEFBQcBAQQsMCowKAYIKwYBBQUHMAGGHGh0dHA6Ly9wa2ktb2NzcC5kaWdpY2VydC5jb20wHwYDVR0jBBgwFoAU4CxNUItAuK6m/jcfp/tnenaMOAswDQYJKoZIhvcNAQELBQADggEBACYpdF6tOSLU5H8Jnx+JEDQAaibRqHUPicID39QHTZgpwWRchGinmxqrSesvtfwp+lhrmTAHQE9LWyO/EMmgu/35Estf/9eUKYVSFNAxfrMDoK6Wc+lth5heiXsUM+2DdFRr7K2C+zFrgH9fuqpvS8H+ngMKX1iVQAYJL1JPiXCasblt+tAeI2W5tytoDTHp9kWOmqD/0OIQ7zpq6nMoIQKmuk96h+SuT3QMVXter1JKIaoud0sOec5sjPRiTQnArK2/DUQHwwc/EqTgtrJ+Yqe8Vs8WCsx3rLcj0xLZGfW5XqqqcwLcseX95K/5ow6Ns51ftQG8j0w5RJzielE1o/A="
      ],
      "alg": "PS256"
    }
  ]
}
```


## Mock JWKS:

```
{
  "keys": [
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "AA24F185EE3F67504808FC4E26B135B99E63BDA9",
      "x5t": "qiTxhe4_Z1BICPxOJrE1uZ5jvak",
      "e": "AQAB",
      "n": "wJzMeVghWUqNL992TiwsOg0X10K9kwQNvk8tL7vKxFV5dfSZkzxikzdXWFGdxmUIxrXoWjCRv3C0FleHSz6z1_FyJwwj_h9EfUBASMkliA8S9yWDLV7IOfExA1DxwF0EmsEkb6JUvd0drsOwVAWk4mRhla77ENZi2PKx9KWhimMUbwycRpUYX2jWBLAkKxYNBNtLKERfSJ3Um_6Mzq5liztJJPQxVkbahtGN0bu5EmWipz3vgFOp9L4noks2MUmCq0fHXKXR0fd_l3liLREVxW-ilWEQkvHGvqDthzLWiI8IwmHmg7TMnP1iVtsWxtT1fWd2HPbBKSHYtNrfvrxF-w",
      "x5c": [
        "MIIEyTCCArGgAwIBAgIUK4Ey/GzkJrCnJVK4kAo39VvCsC8wDQYJKoZIhvcNAQELBQAwYTELMAkGA1UEBhMCQVUxDDAKBgNVBAgMA0FDVDERMA8GA1UEBwwIQ2FuYmVycmExDTALBgNVBAoMBEFDQ0MxDDAKBgNVBAsMA0NEUjEUMBIGA1UEAwwLTW9jayBDRFIgQ0EwHhcNMjEwNDEzMjIxODIwWhcNMjIwNTE4MjIxODIwWjBfMRIwEAYDVQQDDAlsb2NhbGhvc3QxCzAJBgNVBAYTAkFVMQwwCgYDVQQIDANBQ1QxETAPBgNVBAcMCENhbmJlcnJhMQ0wCwYDVQQKDARBQ0NDMQwwCgYDVQQLDANDRFIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAnMx5WCFZSo0v33ZOLCw6DRfXQr2TBA2+Ty0vu8rEVXl19JmTPGKTN1dYUZ3GZQjGtehaMJG/cLQWV4dLPrPX8XInDCP+H0R9QEBIySWIDxL3JYMtXsg58TEDUPHAXQSawSRvolS93R2uw7BUBaTiZGGVrvsQ1mLY8rH0paGKYxRvDJxGlRhfaNYEsCQrFg0E20soRF9IndSb/ozOrmWLO0kk9DFWRtqG0Y3Ru7kSZaKnPe+AU6n0vieiSzYxSYKrR8dcpdHR93+XeWItERXFb6KVYRCS8ca+oO2HMtaIjwjCYeaDtMyc/WJW2xbG1PV9Z3Yc9sEpIdi02t++vEX7AgMBAAGjezB5MB8GA1UdIwQYMBaAFIMGntq6COYrCVIIYmzeFKQXdnVRMAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgXgMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMBMCMGA1UdEQQcMBqCCWxvY2FsaG9zdIINcmVnaXN0ZXIubW9jazANBgkqhkiG9w0BAQsFAAOCAgEALChKDaW7tomVssJ8ji9C99siAd4FPMWmmJixPieaeIdUuiyYcuizwfBP5/R6Bx7SJ84uQJE5M/xIB2WTLHgAPh0aYeoGQzOFQlc9h8Qjaj4DUFchd53FS83vXQW+PQk74ViT4Pw6O0VHujjqfQ8jDPvzg/mFWhtyrIDx0/rgCDQ9Maqj84Hw0J9jA+RTKmYma5ZAG1c/1AQVYX9yebh1wZA4tkyUQTupY2HO4YPJ2xLliUBWj70bgkSGi971ykScKTmlUKrHUFvOA9LBNJg14Mm5EXXDVH4Cf7KEmZLM8BaaHRLMm5TY1Hv0TKJLCPGMKPcqEQAfLmuCZaC4bWS5C5Xwv+P4nFjYZTk3OOiHT9vu16bXzEo3P4yfioDCXRqq922+XOGW/PVrmqdGAL/iOxu0RuaFY9LJl2Hz/6pXs6HhSSeJIqUs7Lt0n20APjcmdZmrtdI0KbVOx1Swg4aRdRTfXEayOfDhwk05ULUx7dJIhCt8C+ODx7ayu727DlQRtbd21UuEUHUXGfUoUSHdNh1ypgt9vhNMbbaEAp84nlppOejiDKv/X/4jkYQR2URByT+hoD/quDlDWLfui5lzVqLN9c9zLQKzQMD13QHAJ1EMKSlCzkfc2ySZEiI74i1yu29xVbiksVE+lgBAVF55Z4TIRpEiChHMfKQCKtVGgh4="
      ],
      "alg": "PS256"
    }
  ]
}
```

**Comment by steveoshima** [comment]
Thanks for the feedback.
We need to raise a bug with that team to say its NOT following the correct RFC standards for the kid and x5t.

In not following the standards it will mean "data holder" devs will have to work around this defect, adding code and certificate lookups in places that should not be required.
i.e. creating the id_token requires a private key for signing. The private key is converted to JWK and from that the kid placed in the id_token JWT header. If we now have to use an x5t as the kid value (breaking the RFC standards) then we need to also fetch the public DER cert and use other libraries to build the thumbprint.
The ADR devs will also face similar workarounds.

**Comment by steveoshima** [comment]
Raised a ticket with production CDR register - https://github.com/cdr-register/register/issues/184

**Comment by steveoshima** [comment]
Hi, I see a response from the production CDR register - cdr-register/register#184
They are using the correct kid values as defined by the standards. You can see in this example endpoint - 
https://api.cdr.gov.au/cdr-register/v1/jwks which validates SSAs.

It would be really helpful if you could correct the kid values in turn to match the production cdr register JWKS standards.
We really wish to use this awesome project, the community cannot use this until this bug is fixed. 
Thanks.

**Comment by kenoby-dev** [comment]
**For the x5t issue raised:**

We use an out-of-the-box auth server to generate the JWKS at `/idp/.well-known/openid-configuration/jwks`.  That auth server implementation uses a Microsoft .NET library under the covers to generate the `kid` and the `x5t` values.

As per RFC 7517, the x5t parameter "is a **base64url-encoded** SHA-1 thumbprint (a.k.a. digest) of the DER encoding of an X.509 certificate".   

Using the following bash script over the X509 certificate we use to generate the JWKS, the `x5t` value is calculated as `qiTxhe4_Z1BICPxOJrE1uZ5jvak`.  This is the value that is included in the JWKS.

```
x5c=$(openssl x509 -outform der -in register.pem|base64)
x5t=`echo $x5c|base64 -d|openssl sha1 -binary|base64|tr -d '='|tr '/+' '_-'`
echo $x5t
```

Running an x5t validator (https://github.com/zuldigital/jwks-x5t-validator) across the JWKS also returns a successful match.  

This validator is also successful when validating Microsoft's common JWKS (https://login.microsoftonline.com/common/discovery/v2.0/keys):

```
Validating x5t from JWKS at: https://login.microsoftonline.com/common/discovery/v2.0/keys

  kid: nOo3ZDrODXEK1jKWhXslHR_KXEg
  x5t: nOo3ZDrODXEK1jKWhXslHR_KXEg

[SUCCESS] x5t matches computed x5t

...
```

An example from Open Banking UK (https://keystore.openbanking.org.uk/0015800000jf7AeAAI/0015800000jf7AeAAI.jwks) almost validates successfully, but they don't seem to be using base64url encoding, just standard base64 encoding (which is not to spec):

```
Validating x5t from JWKS at: https://keystore.openbanking.org.uk/0015800000jf7AeAAI/0015800000jf7AeAAI.jwks

  kid: CQeSy9E6FceUMcCE7Q9z5uTvyU8
  x5t: CjyaYemNGvq3yrPkfKiHWn3I4bU=

[FAIL] => computed x5t: CjyaYemNGvq3yrPkfKiHWn3I4bU
```

I note that another auth server (Auth0) had an issue with their implementation of the `x5t` field previously where they were base64url encoding the hex representation of the thumbprint, not the binary.  They have since fixed this issue:
- https://community.auth0.com/t/jwk-certificate-thumbprint-is-invalid/16070/16

Therefore, to me, it looks like we are outputting the correct `x5t` value in our JWKS endpoint.

**Comment by steveoshima** [comment]
Hi thanks for the validation of the x5t. Yes the suffixed '=' is a known issue I believe.

However, our main point was about fixing the kid values according to https://datatracker.ietf.org/doc/html/rfc7638#section-3.2
i.e. "kid": "AA24F185EE3F67504808FC4E26B135B99E63BDA9"
As we can see, this is wrong now that we refer to rfc and the live cdr register jwks.
Will a fix be actioned?

**Comment by ACCC-DF** [comment]
The Production Register does not use the RFC 7638 algorithm to generate the `kid` used in the SSA JWKS endpoint (https://api.cdr.gov.au/cdr-register/v1/jwks) nor in the OIDC JWKS endpoint (https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks).

If the Production Register is ever changed to use the algorithm outlined in RFC 7638, then the Mock Register will be changed accordingly.

**Comment by steveoshima** [comment]
Can you let us know what method is being used to calculate the kid value for 
http://localhost:7000/cdr-register/v1/jwks
vs
https://api.cdr.gov.au/cdr-register/v1/jwks
They look to be different methods.

Thanks, we appreciate the effort in response.

**Comment by ACCC-DF** [comment]
I've confirmed with the Production Register team that the reason the key format is different with the Mock Register between those 2 jwks endpoints is based on the technology used to generate the jwks.

The Mock Register uses a certificate to generate the jwks endpoint so that it is self-contained and portable, whilst the Production Register is a hosted solution that leverages resources available in the platform to generate the jwks.

Regardless, this key id should be treated as an opaque string for key lookup within the jwks.

**Comment by ACCC-DF** [comment]
No further information provided, so will close this issue.

Please feel free to raise a new issue if new information is presented.
