### ISSUE TITLE
How to get the Banking APIs related responses

### ISSUE THREAD

**Issue by gobi-it** [ConsumerDataRight/mock-register#2]
How to get the below details
1.getbank
2.getbulkBalance
3.get account and transaction details

where to get below headers
x-fapi-interaction-id: string
x-fapi-auth-date: string
x-fapi-customer-ip-address: string
x-cds-client-headers: string

![image](https://user-images.githubusercontent.com/59651955/120770687-0951d680-c53c-11eb-8811-cd9f79d48a9e.png)

**Comment by ACCC-DF** [comment]
Hi @gobi-it 

The issues raised here should be specific to the CDR Mock Register.

The CDR Mock Register does not contain the Banking APIs, as these are implemented within a Data Holder solution.

If you have more general questions about CDR or the Consumer Data Standards, please raise a question via the [CDR Support Portal](https://cdr-support.zendesk.com/hc/en-us).
