### ISSUE TITLE
SSA org_id and software_id values look incorrect.

### ISSUE THREAD

**Issue by steveoshima** [ConsumerDataRight/mock-register#20]
**Describe the bug**
Generating the SSA looking at org_id and software_id values:

They seem to be wrong way around - 
org_id guid is showing the softwareProductId
software_id is showing the BrandId

**To Reproduce**
1. See seed-data.json
2. See https://localhost:7001/cdr-register/v1/banking/data-recipients/brands/F3F0C40B-9DF8-491A-AF1D-81CB9AB5F021/software-products/6F7A1B8E-8799-48A8-9011-E3920391F713/ssa
3. See nested SSA JWT org_id software_id

**Expected behaviour**
org_id = BrandId
software_id = softwareProductId

**Comment by ACCC-DF** [comment]
Hi @steveoshima 

Thanks for raising.

Looking at the issue I see the [seed-data.json](https://github.com/ConsumerDataRight/mock-register/blob/main/Source/CDR.Register.Admin.API/Data/seed-data.json) file has the following for the "yoyo Software Company":

```
"Brands": [
{
	"BrandId": "f3f0c40b-9df8-491a-af1d-81cb9ab5f021",
	"BrandName": "YoYo",
	"LogoUri": "https://yoyosoftware/img/logo.png",
	"BrandStatusId": 1, // Map internally
	"LastUpdated": "2021-04-06T11:58:00",
	"SoftwareProducts": [
	{
		"SoftwareProductId": "6f7a1b8e-8799-48a8-9011-e3920391f713",
```

Whereby:
```
BrandId = "f3f0c40b-9df8-491a-af1d-81cb9ab5f021"
SoftwareProductId = "6f7a1b8e-8799-48a8-9011-e3920391f713"
```

If I call the Get SSA endpoint for that software product (https://localhost:7001/cdr-register/v1/banking/data-recipients/brands/F3F0C40B-9DF8-491A-AF1D-81CB9AB5F021/software-products/6F7A1B8E-8799-48A8-9011-E3920391F713/ssa) I receive the following SSA:

```
eyJhbGciOiJQUzI1NiIsImtpZCI6IjU0MkE5QjkxNjAwNDg4MDg4Q0Q0RDgxNjkxNkE5RjQ0ODhERDI2NTEiLCJ0eXAiOiJKV1QifQ.ew0KICAicmVjaXBpZW50X2Jhc2VfdXJpIjogImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcCIsDQogICJsZWdhbF9lbnRpdHlfaWQiOiAiZGU4MTVhOTMtODViMy00ZmU4LTk1MTMtMzNhZDhmNDM1OWQwIiwNCiAgImxlZ2FsX2VudGl0eV9uYW1lIjogInlveW8gU29mdHdhcmUgQ29tcGFueSIsDQogICJpc3MiOiAiY2RyLXJlZ2lzdGVyIiwNCiAgImlhdCI6IDE2MjU2OTQxMjMsDQogICJleHAiOiAxNjI1Njk0NzIzLA0KICAianRpIjogImM4MjdmNGE5MGYxNTQyZDA4NWNkYmU2MmYwOTljMWJlIiwNCiAgIm9yZ19pZCI6ICJmM2YwYzQwYi05ZGY4LTQ5MWEtYWYxZC04MWNiOWFiNWYwMjEiLA0KICAib3JnX25hbWUiOiAiWW9ZbyIsDQogICJjbGllbnRfbmFtZSI6ICJNeUJ1ZGdldEhlbHBlciIsDQogICJjbGllbnRfZGVzY3JpcHRpb24iOiAiQSBwcm9kdWN0IHRvIGhlbHAgeW91IG1hbmFnZSB5b3VyIGJ1ZGdldCIsDQogICJjbGllbnRfdXJpIjogImh0dHBzOi8veW95b3NvZnR3YXJlL215YnVkZ2V0YXBwIiwNCiAgInJlZGlyZWN0X3VyaXMiOiBbDQogICAgImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9jYWxsYmFjayIsDQogICAgImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9yZXR1cm4iDQogIF0sDQogICJsb2dvX3VyaSI6ICJodHRwczovL3lveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9pbWcvbG9nby5wbmciLA0KICAidG9zX3VyaSI6ICJodHRwczovL3lveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC90ZXJtcyIsDQogICJwb2xpY3lfdXJpIjogImh0dHBzOi8veW95b3NvZnR3YXJlL215YnVkZ2V0YXBwL3BvbGljeSIsDQogICJqd2tzX3VyaSI6ICJodHRwczovL2xvY2FsaG9zdDo3MDA2L2xvb3BiYWNrL01vY2tEYXRhUmVjaXBpZW50SndrcyIsDQogICJyZXZvY2F0aW9uX3VyaSI6ICJodHRwczovL2FwaS55b3lvc29mdHdhcmUvbXlidWRnZXRhcHAvcmV2b2tlIiwNCiAgInNvZnR3YXJlX2lkIjogIjZmN2ExYjhlLTg3OTktNDhhOC05MDExLWUzOTIwMzkxZjcxMyIsDQogICJzb2Z0d2FyZV9yb2xlcyI6ICJkYXRhLXJlY2lwaWVudC1zb2Z0d2FyZS1wcm9kdWN0IiwNCiAgInNjb3BlIjogIm9wZW5pZCBwcm9maWxlIGJhbms6YWNjb3VudHMuYmFzaWM6cmVhZCBiYW5rOmFjY291bnRzLmRldGFpbDpyZWFkIGJhbms6dHJhbnNhY3Rpb25zOnJlYWQgYmFuazpwYXllZXM6cmVhZCBiYW5rOnJlZ3VsYXJfcGF5bWVudHM6cmVhZCBjb21tb246Y3VzdG9tZXIuYmFzaWM6cmVhZCBjb21tb246Y3VzdG9tZXIuZGV0YWlsOnJlYWQgY2RyOnJlZ2lzdHJhdGlvbiINCn0.jXyL0QamO1kUF7DUCGvmHMKwdZzoaknstigYSH-yYJqEv5KtVNdgGT_wYXytgXCCfBM0Tp22zxZvT7wMUQY0X69gTxiLMQSlsgF7iCbj94HIDHqM3le-DYmMW6kSww8UotDR5woZHDhVw3XiLN4DwaUowaFQ39Y2rh477pGx4FW-6WVOnw2Q-T8XUHom8iiuX-UhI9LoOXHt_tw9zY9DDDZts4Ti7xYNC--SFfA3p2EStYVE6RH_eGYNkp9sullUeWjnmniltglzxsFEknQqUcVIIEkM3jM2me9n4DPGgbBjZjkK9EoeBIHwG-MKRGuj1Z8EO9Ls8T9DHNgZ4DNWiA
```

Which [decoded](https://jwt.io/?token=eyJhbGciOiJQUzI1NiIsImtpZCI6IjU0MkE5QjkxNjAwNDg4MDg4Q0Q0RDgxNjkxNkE5RjQ0ODhERDI2NTEiLCJ0eXAiOiJKV1QifQ.ew0KICAicmVjaXBpZW50X2Jhc2VfdXJpIjogImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcCIsDQogICJsZWdhbF9lbnRpdHlfaWQiOiAiZGU4MTVhOTMtODViMy00ZmU4LTk1MTMtMzNhZDhmNDM1OWQwIiwNCiAgImxlZ2FsX2VudGl0eV9uYW1lIjogInlveW8gU29mdHdhcmUgQ29tcGFueSIsDQogICJpc3MiOiAiY2RyLXJlZ2lzdGVyIiwNCiAgImlhdCI6IDE2MjU2OTQxMjMsDQogICJleHAiOiAxNjI1Njk0NzIzLA0KICAianRpIjogImM4MjdmNGE5MGYxNTQyZDA4NWNkYmU2MmYwOTljMWJlIiwNCiAgIm9yZ19pZCI6ICJmM2YwYzQwYi05ZGY4LTQ5MWEtYWYxZC04MWNiOWFiNWYwMjEiLA0KICAib3JnX25hbWUiOiAiWW9ZbyIsDQogICJjbGllbnRfbmFtZSI6ICJNeUJ1ZGdldEhlbHBlciIsDQogICJjbGllbnRfZGVzY3JpcHRpb24iOiAiQSBwcm9kdWN0IHRvIGhlbHAgeW91IG1hbmFnZSB5b3VyIGJ1ZGdldCIsDQogICJjbGllbnRfdXJpIjogImh0dHBzOi8veW95b3NvZnR3YXJlL215YnVkZ2V0YXBwIiwNCiAgInJlZGlyZWN0X3VyaXMiOiBbDQogICAgImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9jYWxsYmFjayIsDQogICAgImh0dHBzOi8vYXBpLnlveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9yZXR1cm4iDQogIF0sDQogICJsb2dvX3VyaSI6ICJodHRwczovL3lveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC9pbWcvbG9nby5wbmciLA0KICAidG9zX3VyaSI6ICJodHRwczovL3lveW9zb2Z0d2FyZS9teWJ1ZGdldGFwcC90ZXJtcyIsDQogICJwb2xpY3lfdXJpIjogImh0dHBzOi8veW95b3NvZnR3YXJlL215YnVkZ2V0YXBwL3BvbGljeSIsDQogICJqd2tzX3VyaSI6ICJodHRwczovL2xvY2FsaG9zdDo3MDA2L2xvb3BiYWNrL01vY2tEYXRhUmVjaXBpZW50SndrcyIsDQogICJyZXZvY2F0aW9uX3VyaSI6ICJodHRwczovL2FwaS55b3lvc29mdHdhcmUvbXlidWRnZXRhcHAvcmV2b2tlIiwNCiAgInNvZnR3YXJlX2lkIjogIjZmN2ExYjhlLTg3OTktNDhhOC05MDExLWUzOTIwMzkxZjcxMyIsDQogICJzb2Z0d2FyZV9yb2xlcyI6ICJkYXRhLXJlY2lwaWVudC1zb2Z0d2FyZS1wcm9kdWN0IiwNCiAgInNjb3BlIjogIm9wZW5pZCBwcm9maWxlIGJhbms6YWNjb3VudHMuYmFzaWM6cmVhZCBiYW5rOmFjY291bnRzLmRldGFpbDpyZWFkIGJhbms6dHJhbnNhY3Rpb25zOnJlYWQgYmFuazpwYXllZXM6cmVhZCBiYW5rOnJlZ3VsYXJfcGF5bWVudHM6cmVhZCBjb21tb246Y3VzdG9tZXIuYmFzaWM6cmVhZCBjb21tb246Y3VzdG9tZXIuZGV0YWlsOnJlYWQgY2RyOnJlZ2lzdHJhdGlvbiINCn0.jXyL0QamO1kUF7DUCGvmHMKwdZzoaknstigYSH-yYJqEv5KtVNdgGT_wYXytgXCCfBM0Tp22zxZvT7wMUQY0X69gTxiLMQSlsgF7iCbj94HIDHqM3le-DYmMW6kSww8UotDR5woZHDhVw3XiLN4DwaUowaFQ39Y2rh477pGx4FW-6WVOnw2Q-T8XUHom8iiuX-UhI9LoOXHt_tw9zY9DDDZts4Ti7xYNC--SFfA3p2EStYVE6RH_eGYNkp9sullUeWjnmniltglzxsFEknQqUcVIIEkM3jM2me9n4DPGgbBjZjkK9EoeBIHwG-MKRGuj1Z8EO9Ls8T9DHNgZ4DNWiA) gives me:
```
{
  "recipient_base_uri": "https://api.yoyosoftware/mybudgetapp",
  "legal_entity_id": "de815a93-85b3-4fe8-9513-33ad8f4359d0",
  "legal_entity_name": "yoyo Software Company",
  "iss": "cdr-register",
  "iat": 1625694123,
  "exp": 1625694723,
  "jti": "c827f4a90f1542d085cdbe62f099c1be",
  "org_id": "f3f0c40b-9df8-491a-af1d-81cb9ab5f021",
  "org_name": "YoYo",
  "client_name": "MyBudgetHelper",
  "client_description": "A product to help you manage your budget",
  "client_uri": "https://yoyosoftware/mybudgetapp",
  "redirect_uris": [
    "https://api.yoyosoftware/mybudgetapp/callback",
    "https://api.yoyosoftware/mybudgetapp/return"
  ],
  "logo_uri": "https://yoyosoftware/mybudgetapp/img/logo.png",
  "tos_uri": "https://yoyosoftware/mybudgetapp/terms",
  "policy_uri": "https://yoyosoftware/mybudgetapp/policy",
  "jwks_uri": "https://localhost:7006/loopback/MockDataRecipientJwks",
  "revocation_uri": "https://api.yoyosoftware/mybudgetapp/revoke",
  "software_id": "6f7a1b8e-8799-48a8-9011-e3920391f713",
  "software_roles": "data-recipient-software-product",
  "scope": "openid profile bank:accounts.basic:read bank:accounts.detail:read bank:transactions:read bank:payees:read bank:regular_payments:read common:customer.basic:read common:customer.detail:read cdr:registration"
}
```

Whereby:
```
org_id (i.e. BrandId)= "f3f0c40b-9df8-491a-af1d-81cb9ab5f021"
software_id (i.e. SoftwareProductId)= "6f7a1b8e-8799-48a8-9011-e3920391f713"
```

Therefore, to me the current behaviour is working as expected.  Please confirm what you are seeing.

**Comment by steveoshima** [comment]
Ok, sorry about that. Yea it is looking correct.
