### ISSUE TITLE
Need clarification regarding Certificate "register.pfx and clent.key"

### ISSUE THREAD

**Issue by gobi-it** [ConsumerDataRight/mock-register#26]
Hi,
I Need clarification regarding the Certificate 
1.What is the purpose of a certificate?
2.In production where to get the certificates?
Ex:register.pfx, ca.crt, ca.pem, tls-register.pfx
![image](https://user-images.githubusercontent.com/59651955/126751228-a44bb67d-8d8b-4986-8276-f89445cbd461.png)

3.why do we use a private key in the solution
![image](https://user-images.githubusercontent.com/59651955/126751900-e056c2e8-c1b5-4304-a824-34ad5c6a091a.png)

4.What is the purpose of the certificate? it's necessary or not for our own Solution

**Comment by ACCC-DavidR** [comment]
Hi @gobi-it 

Please refer to the following links which should provide some additional context to the questions related to certificates in the Mock Register, and within the Production CDR environment.

> 1. What is the purpose of a certificate?

Please refer to https://github.com/ConsumerDataRight/mock-register/blob/main/CertificateManagement/README.md

This link should provide some additional information around certificates, and notes the following 

> The Mock Register will mimic the behaviour of the CDR ecosystem and therefore will use certificates in its interactions. However, the use of DigiCert for this person is not feasible or scalable so an alternative approach must be adopted.

> 2. In Production where to get the certificates?

Please refer to https://cdr-register.github.io/register/#certificate-management

This link provides additional details about certificate management in a production environment, including where they can be obtained.

> DigiCert is the Certificate Authority (CA) for the CDR and the ACCC is responsible for provisioning DigiCert certificates to participants during the on-boarding process.

Thanks

**Comment by ACCC-DavidR** [comment]
No further questions asked, closing for now. Feel free to re-open if you needed additional information.

Thanks
