### ISSUE TITLE
Need Clarification regarding Mock register postman collection

### ISSUE THREAD

**Issue by gobi-it** [ConsumerDataRight/mock-register#27]
Hi,
  1.  I call the "**Discovery API - Get Data Holder Brands (requires access token)**" then I pass bearer token but the response is **Socket hangup** what I do?

![image](https://user-images.githubusercontent.com/59651955/126752538-4c972139-175c-46aa-b641-320e8433e9f6.png)

1.InfoSec - Get OIDC Config I got a 502 bad gateway error, how to rectify this?
![image](https://user-images.githubusercontent.com/59651955/126753061-acc41b8c-57a2-4c51-9097-f82d1e44cdf8.png)

**Comment by ACCC-DavidR** [comment]
Hi @gobi-it 

To run the `Discovery API - Get Data Holder Brands (requires access token)`  you must first run the `InfoSec - Get Access Token` request and copy over the responses `access_token`.

Thanks for raising this, as it's not ideal we have actually gone ahead and changed this over to a global variable to be updated into the main repo shortly which will save you having to manually copy/paste it - see PR #28 

You can either grab the `Postman/mock-register.postman_collection.json` file from the above PR, or in the meantime the following workaround will get you up and running.

1) Run the `InfoSec - Get Access Token` request
2) Copy the `access_token` from the response
4) Paste it into the Authorization header (`Authorization` tab) on the `Discovery API - Get Data Holder Brands (requires access token)` request
3) Run the `Discovery API - Get Data Holder Brands (requires access token)` request

Thanks

**Comment by gobi-it** [comment]
Hi David,
  I am doing what you said above you mentioned  command but I got a socket hang up error please find below image 

![image](https://user-images.githubusercontent.com/59651955/127150095-186ef7b2-fa0f-4586-9469-0a506a5bfe62.png)

**Comment by ACCC-DavidR** [comment]
Hi @gobi-it 

Can you please confirm that you have followed all steps outlined in the [Postman collection README](https://github.com/ConsumerDataRight/mock-register/blob/main/Postman/README.md)

I was able to replicate a socket hang up error before ensuring that the mtls client.pfx certificate had been setup in Postman.
The steps to set this up are outlined in the README.md file within this project at `/Postman/README.md`

> 1. In the Postman app, click on the Settings option from the File menu.
> 2. In the Settings window, click on the Certificates tab and then on the Add Certificate option.
> 3. Add the client.pfx certificate for all requests to https://localhost:7001
> 4. The client.pfx certificate should now be sent to all Postman requests to the Mock Register mTLS endpoint - https://localhost:7001.

Thanks

**Comment by gobi-it** [comment]
Hi,
Yes I already added the certificates 
![image](https://user-images.githubusercontent.com/59651955/127263897-dc25aa41-ab89-4a9a-8141-80b8aef879de.png)

**Comment by ACCC-DavidR** [comment]
Hi @gobi-it 

Just also want to confirm that that is the same pfx file from `/CertificateManagement/mtls/client.pfx` ?
An incorrect pfx will also cause a socket hang up.

Thanks

**Comment by gobi-it** [comment]
Hi @CDR-DavidR 
Yes, Same client.pfx only I added

**Comment by gobi-it** [comment]
Hi @CDR-DavidR ,
Have you added the main repo to PR #28?

**Thanks for raising this, as it's not ideal we have actually gone ahead and changed this over to a global variable to be updated into the main repo shortly which will save you having to manually copy/paste it - see PR #28**

**Comment by ACCC-DavidR** [comment]
Hi @gobi-it 

The team have unfortunately been unable to replicate your issue.
Our advice is to `git clone` a fresh copy of the repo and try and run it and the Postman collection again without moving any of the files.
Give that a shot and let me know how you go. Also just to check are you running the .NET project directly or using the docker container?

As for the PR, I'll get someone in the team to review it in the coming days.
In the meantime if you are after the [Updated Postman Collection, you can use this link to go directly to it](https://github.com/ConsumerDataRight/mock-register/blob/fd285e04bf215d1e97c48c3065504e19147d5949/Postman/mock-register.postman_collection.json) and just import it instead.

Thanks

**Comment by gobi-it** [comment]
Hi @CDR-DavidR ,
I am running a .NET project directly
