### ISSUE TITLE
Need clarification regarding Kestrel  web server

### ISSUE THREAD

**Issue by gobi-it** [ConsumerDataRight/mock-register#29]
Hi,
In mock-register source what is the purpose of using kestrel, please explain, it's required?

![image](https://user-images.githubusercontent.com/59651955/127600957-e39ca030-51f2-4604-9903-1c320087b837.png)

**Comment by ACCC-DavidR** [comment]
Hi @gobi-it 

Kestrel is the web server that has been used to expose the APIs within the project.
Let me know if you are after anything specific with this question.

Thanks
