### ISSUE TITLE
Missing 'use' property in the Mock DR JWKS response

### ISSUE THREAD

**Issue by Dinushi** [ConsumerDataRight/mock-register#30]
**Describe the bug**

The MockDataRecipientJwks endpoint (https://localhost:7006/loopback/MockDataRecipientJwks) is currently returning the public keys' information in the JWKS format without including the property - '**use**' (Public Key Use).

> Use : Implies how the key is being used. The value sig represents signature.

When this jwks endpoint is used in our DH solutions for scenarios such as encrypting JWT responses and the presence of property 'use' with either '**enc**'  or '**sig**' as the value is mandatory, the flows can not be proceeded.

Hence, the Mock DR JWKS can be more useful if the current JWKS can be updated with the 'use' property with the value as '**sig**'.
(Since the '**key_ops**' values of the current JWKS are '**sign**' and '**verify**', only '**sig**' can be used as the value for 'use')

But as a further improvement, the JWKS endpoint can be improved to add more separate jwk sets with **key_ops** having '**encrypt**' and 'use' property as '**enc**'.

As a temporal solution, the following fix was done.
1. The JsonWebKey.cs model [1] was updated with the 'use' attribute by adding the following line.

    `public string use { get; set; }`

2. The LoopbackController.cs jwk generation [2] is updated by adding the following line.

    `use = "sig",`

[1] https://github.com/ConsumerDataRight/mock-register/blob/cc301185b0f6085125f41e12807aad960a75b03c/Source/CDR.Register.API.Infrastructure/Models/JsonWebKey.cs#L5
[2] https://github.com/ConsumerDataRight/mock-register/blob/cc301185b0f6085125f41e12807aad960a75b03c/Source/CDR.Register.Admin.API/Controllers/LoopbackController.cs#L43

**To Reproduce**

1. Call the https://localhost:7006/loopback/MockDataRecipientJwks endpoint.
2. Notice that the 'use' property is missing in the returned jwks.

```
{
    "keys": [
        {
            "alg": "PS256",
            "e": "AQAB",
            "key_ops": [
                "sign",
                "verify"
            ],
            "kid": "gP32GTv0be7hGek1ONMPg0T6P4RrKtRLl4l0em7XCw4",
            "kty": "RSA",
            "n": "6kpKQ674ZD6dCrJaZezah4Hpr8D5xo4Pn4TibDtWqWr42ghq2SdJ09laHil4h1t-9u3YLbLeNQlbq2izyvQv_l8mWfBRqb7-UgEfT4EFAlriD5h84xsbsK85laz7ph7LA8kj11ztxuUqjeGbircng2v6GM8nzMSk8n4g9nNSy3-G0nZcPYPqYcbISwPiFX9RN4aPKysouuJ1k1IIVdPzUVaAQwP5F9R7TEz1lWkD4Lj1nw-mx6Jxe5fiozuMS87rD8A9AXtuO-57pmW_m40fiDJRF7csYOYL1N32AUcIIrJW0KYdImWtaOMm-mAAlbGX2zz3znXElKaEm0rBqZdx5Q"
        }
    ]
}
```

**Expected behaviour**

The returned response from the MockDataRecipientJwks endpoint should be as follows.

```
{
    "keys": [
        {
            "alg": "PS256",
            "use": "sig",
            "e": "AQAB",
            "key_ops": [
                "sign",
                "verify"
            ],
            "kid": "gP32GTv0be7hGek1ONMPg0T6P4RrKtRLl4l0em7XCw4",
            "kty": "RSA",
            "n": "6kpKQ674ZD6dCrJaZezah4Hpr8D5xo4Pn4TibDtWqWr42ghq2SdJ09laHil4h1t-9u3YLbLeNQlbq2izyvQv_l8mWfBRqb7-UgEfT4EFAlriD5h84xsbsK85laz7ph7LA8kj11ztxuUqjeGbircng2v6GM8nzMSk8n4g9nNSy3-G0nZcPYPqYcbISwPiFX9RN4aPKysouuJ1k1IIVdPzUVaAQwP5F9R7TEz1lWkD4Lj1nw-mx6Jxe5fiozuMS87rD8A9AXtuO-57pmW_m40fiDJRF7csYOYL1N32AUcIIrJW0KYdImWtaOMm-mAAlbGX2zz3znXElKaEm0rBqZdx5Q"
        }
    ]
}
```

**Screenshots**

**Additional context**

**Comment by CDR-CT** [comment]
This is not really a bug. Could be an enhancement.

Use of the "use" property is optional, unless the application requires its presence and it could be different from application to application. If your DH application needs it, it's expected that you change it according to your requirements (It seems you have already done and which is good).

Furthermore, this MockDataRecipientJwks endpoint (https://localhost:7006/loopback/MockDataRecipientJwks) is a temporary solution until we get our mock data holder and the mock data recipient solutions in place. Once they are ready, there will be a new jwks endpoint in the mock data recipient with multiple keys with multiple 'use' and 'alg' values.

**Comment by ACCC-DavidR** [comment]
Closing for now, feel free to reopen if the above didn't answer your query.

Thanks

**Comment by Dinushi** [comment]
Yeah, I accept that this should be an enhancement.

Though 'use' is an optional attribute, it will be more usable if this could be added to the existing mock ADR jwks endpoint for now. It removes the burden of changing the source code of mock-register, build and maintain a custom docker image to execute automated test cases that utilize this mock CDR register. (Then, we can directly pull the docker image published by ACCC team and utilize that during our automated test execution)
