### ISSUE TITLE
My client_assertion won't work to get access_token

### ISSUE THREAD

**Issue by katarina-basiq** [ConsumerDataRight/mock-register#37]
**Describe the bug**
Hello there!
We have deployed Mock Register on our instance in order to use it for testing our ADR solution. In order to mimic ADR I successfully loaded my data via Admin API - Load Metadata endpoint. To simplify debugging I put minimal changes to my data comparing to your payload for loading metadata. Actually I just changed JwksUri endpoint to invoke my server's endpoint for jwk keys, all other id's and properties stay the same as original. I changed this because I wanted to use client_assertion created by me in order to retrieve access_token on endpoint InfoSec - Get Access Token instead of calling  Admin API - Get Mock DR Client Assertion for getting client_assertion. SoftwareProductId and BrandGuid are the same as in your postman collection. After this configuration I got "invalid_client" response on InfoSec - Get Access Token. I don't know if configuration I did is enough to get valid client's access_token, but couldn't find more info on docs. 
Do you have any suggestions there, how could I achieve this? Is it feasible at all with current Mock Register?

**To Reproduce**
Steps to reproduce the behaviour:
1. This is cUrl request how I loaded my metadata 

> curl --location --request POST 'https://mock-cdr.basiq-dev.com:7006/admin/metadata' \
--header 'Content-Type: application/json' \
--data-raw '{
	"LegalEntities": [{
		"LegalEntityId": "de815a93-85b3-4fe8-9513-33ad8f4359d0",
		"LegalEntityName": "yoyo Software Company",
		"LogoUri": "https://yoyosoftware/img/logo.png",
		"Abn": "11222333444",
		"Acn": "222333444",
		"AccreditationNumber": "ADRBNK000005",
		"Participations": [{
			"ParticipationId": "0fbc379d-8e48-4dcd-90d3-c13862889e83",
			"LegalEntityId": "de815a93-85b3-4fe8-9513-33ad8f4359d0",
			"ParticipationTypeId": 2,
			"IndustryId": 1,
			"StatusId": 1,
			"Brands": [{
				"BrandId": "f3f0c40b-9df8-491a-af1d-81cb9ab5f021",
				"BrandName": "YoYo",
				"LogoUri": "https://yoyosoftware/img/logo.png",
				"BrandStatusId": 1,
				"ParticipationId": "0fbc379d-8e48-4dcd-90d3-c13862889e83",
				"LastUpdated": "2021-04-06T11:58:00",
				"SoftwareProducts": [{
					"SoftwareProductId": "6f7a1b8e-8799-48a8-9011-e3920391f713",
					"SoftwareProductName": "MyBudgetHelper",
					"SoftwareProductDescription": "A product to help you manage your budget",
					"LogoUri": "https://yoyosoftware/mybudgetapp/img/logo.png",
					"ClientUri": "https://yoyosoftware/mybudgetapp",
					"TosUri": "https://yoyosoftware/mybudgetapp/terms",
					"PolicyUri": "https://yoyosoftware/mybudgetapp/policy",
					"RecipientBaseUri": "https://api.yoyosoftware/mybudgetapp",
					"RevocationUri": "https://api.yoyosoftware/mybudgetapp/revoke",
					"RedirectUris": "https://api.yoyosoftware/mybudgetapp/callback https://api.yoyosoftware/mybudgetapp/return",
					"JwksUri": "https://27ghl0gdic.execute-api.ap-southeast-2.amazonaws.com/Development/jwks",
					"Scope": "openid bank:accounts.basic:read bank:accounts.detail:read bank:transactions:read bank:payees:read bank:regular_payments:read common:customer.basic:read common:customer.detail:read cdr:registration",
					"StatusId": 1,
					"BrandId": "f3f0c40b-9df8-491a-af1d-81cb9ab5f021",
					"Certificates": [{
						"SoftwareProductCertificateId": "d3451e00-fe15-46c2-aec1-d82506110ede",
						"SoftwareProductId": "6f7a1b8e-8799-48a8-9011-e3920391f713",
						"CommonName": "MockDataRecipient",
						"Thumbprint": "58D76F7A61CD726DA1C54F6898E8E69EA4C88060"
					}]
				}],
				"AuthDetails": []
			}]
		}]
	}]
}'

2. I invoked Get Access Token per documentation with appropriate claims signed by my private key to get client_assertion and pass all needed params but I keep getting invalid_client error. 
P.S. When I invoke your endpoint Admin API - Get Mock DR Client Assertion and use retrieved client_assertion to get access token (with original config on metadata) I successfully get access_token.

**Expected behaviour**
To get valid access_token after provided setup.

**Screenshots**

**Additional context**
Just to mention here that on endpoint Discovery API - Get Data Holder Brands I keep getting 404 Not found error.

**Comment by CDR-CT** [comment]
Hi @katarina-basiq, 
Usually, the log file contains more information about the error.
Can you please share the full log of the CDR.Register.IdentityServer solution, when you get the "invalid_client" error? (If needed, delete the old error logs and generate a new log file just containing the transactions/logs related to this specific scenario run)

**Comment by katarina-basiq** [comment]
Thank you for fast response!
Here is the log file. The last request from log file is the one of interest for this topic.

[cdr-mr-identityserver.log](https://github.com/ConsumerDataRight/mock-register/files/7195124/cdr-mr-identityserver.log)

**Comment by katarina-basiq** [comment]
Hello there,

I discovered what was the issue. Audience claim was not valid, because it is expected from your side to be `https://localhost:7001/idp/connect/token`. Is there any way I can configure what is returned from InfoSec - Get OIDC Config? That way I can have relevant URLs to real CDR Register, actual URLs where it is hosted.

**Comment by CDR-CT** [comment]
Hi @katarina-basiq,

Yes, it has to be the "token_endpoint" value from the OIDC Discovery Document.
