### ISSUE TITLE
Missing key_ops value

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataRight/mock-register#42]
**Describe the bug**
The .well-known/openid-configuration/jwks endpoint should return a mandatory property key_ops.
This is specified in [here](https://consumerdatastandardsaustralia.github.io/standards/#tocSjwk)

**To Reproduce**

1.  Go the the ACCC jwks endpoint https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks
2.  Examine the returned structure

**Expected behaviour**
Return the key_ops property

**Additional context**

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue.

We have been unable to replicate the documented scenario following the provided steps. Please reach out again if you get a repeat of this issue.
