### ISSUE TITLE
Mock CTS for local development

### ISSUE THREAD

**Issue by danieljeganathan** [ConsumerDataRight/mock-register#43]
Hi Team,

Thanks a lot of the mock-register, mock-data-receipient and mock-data-holder. 
Do we have any mock CTS for local development?
That will highly helpful in our development and testing locally. Identifying defects during our development will be good rather than doing at the end during the CTS.
And it will be helpful for all our FAPI compliance as well.

Thanks,
Daniel Jeganathan

**Comment by CDR-AndrewG** [comment]
Hi,

Thank you for the positive feedback. 

At this moment there are no plans to include CTS with these mock tools. Having a mock CTS is a great suggestion however, that we will take on board.
