### ISSUE TITLE
Endpoint should return 401 instead of 404

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataRight/mock-register#44]
**Describe the bug**
The endpoint https://api.cdr.gov.au/cdr-register/v1/banking/data-holders/brands returns a 404 when NOT authorized. 
The standard specifies that this should return a 401 (see [here](https://consumerdatastandardsaustralia.github.io/standards/#get-data-holder-brands))

**To Reproduce**
1.  Call the above endpoint with an invalid Bearer token in the Authorization header.

**Expected behaviour**
This should return a 401 (Unauthorized)

**Screenshots**
![AcccBugReport](https://user-images.githubusercontent.com/19284769/145142324-c559276e-0a77-4aaa-b89c-4828e961802b.JPG)

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue.

We have been unable to replicate the documented scenario following the provided steps. Please reach out again if you get a repeat of this issue.
