### ISSUE TITLE
Change hostname of "jwks_uri" attribute in SSA to remote IP address instead of localhost

### ISSUE THREAD

**Issue by AmilaSamith** [ConsumerDataRight/mock-register#45]
**Is your feature request related to a problem? Please describe.**
We want to deploy CDR Mock Register container in a remote location for test purposes. So that we need to change hostname value of "jwks_uri" attribute of SSA to relevant IP address of the remote computer replacing localhost. Otherwise we get errors regarding signature_validation due to inability of recognizing  relevant jwks endpoint.

**Describe the solution you'd like**
provide a configuration or  an extension point to set the SSA's jwks_uri attribute. 

**Describe alternatives you've considered**

**Additional context**

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this enhancement request.

Your request has been added to our backlog and will be prioritised amongst our continuous body of work. Our backlog is prioritised based on customer value and is reprioritised as new initiatives arise. As such, we cannot guarantee that this enhancement request will be fulfilled.

Alternatively, we welcome a Pull Request from yourself or the community which we will then review.

**Comment by CDR-AndrewG** [comment]
Hi @AmilaSamith 

The steps outlined in this help file should contain the information you need - [HowToUpdateRegisterHostname.md](https://github.com/ConsumerDataRight/mock-register/blob/main/Help/faq/HowToUpdateRegisterHostname.md)
