### ISSUE TITLE
Change TLS certificate in CDR mock-register

### ISSUE THREAD

**Issue by AmilaSamith** [ConsumerDataRight/mock-register#46]
**Is your feature request related to a problem? Please describe.**
We are using cdr-mock-register while running our test suits. But the issue is that we host that service in a remote location. Therefore we want to change the TLS certificates to be compatible with that server. What we want to know is that, in which locations should we update the new TLS pfx file in ConsumerDataRight/mock-register github repository before running a docker build to create a new image or else is there a way to update that certificate in already running container.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CDR-AndrewG** [comment]
Hi @AmilaSamith 

To use your own tls certificate, replace the **tls** certificate in this folder - https://github.com/ConsumerDataRight/mock-register/tree/main/Source/CDR.Register.API.Gateway.TLS/Certificates

Similarly, if you come across a scenario where you want to use your own mtls certificate, replace the **mtls** certificate in this folder - https://github.com/ConsumerDataRight/mock-register/tree/main/Source/CDR.Register.API.Gateway.mTLS/Certificates

Certificates in the pre-built containers hosted on Docker Hub cannot be updated without requiring a container rebuild. Being able to replace the certificates in a running container is a feature we are looking at internally and have added to our backlog. However, we cannot guarantee that this feature will be approved and added to the solution.

**Comment by AmilaSamith** [comment]
I updated tls certificate in this location(https://github.com/ConsumerDataRight/mock-register/tree/main/Source/CDR.Register.API.Gateway.TLS/Certificates) but it still returns the localhost certificate in TLS handshake.

A issue regarding JWT signature validation occurs in our Dynamic client registration call when calling to endpoint: https://<hostname>:7006/loopback/MockDataRecipientJwks. Do you have any idea why or any thoughts on how we can resolve it.

**Comment by schafer14** [comment]
Hi @CDR-AndrewG,

Is there any status on being able to pass certs to per-built images? That feature would be super valuable. It looks like the certs baked into the container expired today which is an immense pain.

Am I correct in assuming the only way to get around the expired certs (with Docker) is to fork and rebuild the image or wait for the repository to be updated with new certs?

**Comment by CDR-AndrewG** [comment]
Hi @schafer14 ,

Apologies for the inconvenience caused. We are working on a patch release to include updated certificates.

Yes, this feature would be extremely handy right about now.

You are correct. To replace the certificates in the docker container, the certificates in the code repo need to be regenerated and the docker container rebuilt.

There is an extra step if you're building a new client certificate for data recipients to use. The new client certificate's thumbprint would need to be updated in the mock-register database - `cdr-register.dbo.SoftwareProductCertificate.Thumbprint`. Either by updating the database directly or by adding the new thumbprint to the [seed-data file](https://github.com/ConsumerDataRight/mock-register/blob/main/Source/CDR.Register.Admin.API/Data/seed-data.Release.json).

**Comment by schafer14** [comment]
Hi @CDR-AndrewG ,

Thanks for the response. That's good to know. I'll have a go setting that up.

**Comment by schafer14** [comment]
Hi @CDR-AndrewG ,

Those steps got the register working. Thanks. 

I'm now getting some issues when starting up the mock dh. I'm guessing either the mock dh is validating the tls certs for the register have not expired? Do you know what steps I should take to fix this?

**Comment by schafer14** [comment]
All good. I ran this script https://github.com/ConsumerDataRight/mock-register/blob/main/CertificateManagement/tls/mock-data-holder.cmd and that sorted everything out.

**Comment by CDR-AndrewG** [comment]
Hi @schafer14,

All expired certificates have been updated in the [mock-register](https://github.com/ConsumerDataRight/mock-register), [authorisation-server](https://github.com/ConsumerDataRight/authorisation-server), [mock-data-holder](https://github.com/ConsumerDataRight/mock-data-holder), [mock-data-holder-energy](https://github.com/ConsumerDataRight/mock-data-holder-energy) and [mock-data-recipient](https://github.com/ConsumerDataRight/mock-data-recipient) code repositories. 

The latest docker images are available on [Docker Hub](https://hub.docker.com/u/consumerdataright).

**Comment by schafer14** [comment]
Hi @CDR-AndrewG , 

Thanks for doing that. I did fork and create my own image which was pretty straightforward with the instructions.

Thanks.
