### ISSUE TITLE
Unable to build a new docker image after certificate update.

### ISSUE THREAD

**Issue by BenNyanKyaw** [ConsumerDataRight/mock-register#54]
**Describe the bug**
Followed the steps to update mtls cert and got error when a new container is built using the following command.
`docker build -t mock-register-updated .`

I am using macOS, is this solution meant to be only run on Windows system?

**Screenshots**
![image](https://user-images.githubusercontent.com/106580696/171114880-3a6ae991-f75b-421b-b4e7-f334e06f29f9.png)

**Comment by ACCC-DavidR** [comment]
Hi @BenNyanKyaw,

Thanks for reaching out, can you give it a try with the `--no-cache` flag please?
e.g. `docker build --no-cache -t mock-register-updated .`

I am able to build the container on an M1 Pro MacBook Pro running `Docker version 20.10.14, build a224086`
Let us know how you go.

**Comment by BenNyanKyaw** [comment]
Hi @CDR-DavidR,
Thanks for your quick response, I tried again with `--no-cache` but no lucks.
I am on  macOS Catalina, Docker 20.10.11

![image](https://user-images.githubusercontent.com/106580696/171308693-b19faaac-a5c8-496a-860c-a12251b43b72.png)

**Comment by ACCC-DF** [comment]
I have also been able to successfully build the Mock Register container image on my Macbook Pro:

- MacOS Monterey v12.2.1
- Docker v20.10.5

From the log output included above, it looks like there is an issue when accessing `https://api.nuget.org/v3/index.json`?

**Comment by BenNyanKyaw** [comment]
@CDR-DF , looks like something to do with work computer with VPN/proxy. I can build with no issue on my personal mac.

From work mac:
I can hit `https://api.nuget.org/v3/index.json` from both browser and curl inside container.
Do you aware of any setting for ppl using VPN/proxy?

**Comment by ACCC-DavidR** [comment]
That's good news that it is working outside of your work environment at least.
You could try the proxy settings within Docker, as outlined here - https://docs.docker.com/network/proxy/

Hopefully that gets it working for you.

**Comment by BenNyanKyaw** [comment]
Thanks everyone. For other people who faces similar issue, I resolved it by replacing the Nuget config in the container with the following config with additional proxy setting. 

![image](https://user-images.githubusercontent.com/106580696/172082843-b52b18a4-8c54-4b87-b6cc-a17b5677438f.png)
