### ISSUE TITLE
Mock server certificate DN for Register and Data Holder are the same

### ISSUE THREAD

**Issue by ttomttom** [ConsumerDataRight/mock-register#60]
**Describe the bug**
Mock server certificate DN for Register and Data Holder are the same, which makes things a bit confusing. The certificates themselves are different, so that's good, but both CN's are called 'register.mock'. 

Wouldn't it be more straight forward for the server certificate to have CN=mock-data-holder, or something along those lines?

**To Reproduce**
```
$ openssl x509 -subject -noout -in register.pem 
subject=CN = register.mock, C = AU, ST = ACT, L = Canberra, O = ACCC, OU = CDR
```
```
$ openssl x509 -subject -noout -in server.pem 
subject=CN = register.mock, C = AU, ST = ACT, L = Canberra, O = ACCC, OU = CDR
```

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue.

We have logged the issue and will include your suggestion in a future release.

**Comment by CDR-HansenS** [comment]
Hi @ttomttom,

This issue has been rectified in our latest Mock Register production release v.1.3.2
