### ISSUE TITLE
Location for log file in appsettings file is incorrect

### ISSUE THREAD

**Issue by mark202** [ConsumerDataRight/mock-register#65]
In Source/CDR.Register.API.Gateway.TLS/appsettings.Release.json, Logfile location for TLS is set to "c:\\cdr\\Logs\\cdr-mr-gateway-tls.log", this results in the logs being written to the /app folder when running in a container (i.e. absolute Windows path is not understood).

```
        "Name": "File",
        "Args": {
          "path": "c:\\cdr\\Logs\\cdr-mr-gateway-tls.log",
          "outputTemplate": "{Timestamp:dd/MM/yyyy HH:mm:ss.fff zzz} {Level} [{SourceContext}] {Message}{NewLine}{Exception}"
        }
```

The log output should be configured similar to mTLS:

   ```
 "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "File",
        "Args": { "path": "/tmp/cdr-mr-mtls-gateway.log" }
      },
```

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue.

We have logged the issue and will include your suggestion in a future release.

**Comment by CDR-HansenS** [comment]
Hi @mark202, just letting you know that this issue has now been fixed in our latest release today. 

Thank you.
