### ISSUE TITLE
Token call in the postman script is returning invalid_client as response

### ISSUE THREAD

**Issue by aka4rKO** [ConsumerDataRight/mock-register#69]
**Describe the bug**
I have setup the docker container as mentioned in https://github.com/ConsumerDataRight/mock-register/blob/main/Help/container/HELP.md#run-the-mock-register after cloning the latest repository.

Then I used the postman script given here https://github.com/ConsumerDataRight/mock-register/blob/main/Postman/mock-register.postman_collection.json to update the metadata and and invoke the token endpoint.

This call returns the following as a response:
`{
    "error": "invalid_client"
}`

**To Reproduce**
1. Start the container with `docker-compose up -d`
2. Execute the postman request `Admin API - Load Metadata`
3. Execute the postman request `InfoSec - Get Access Token`
4. See the above error

**Expected behaviour**
Return the access token

**Screenshots**

**Additional context**

**Comment by CDR-AndrewG** [comment]
Hi @aka4rKO,

Thank you for getting in touch with us to raise this issue.

Can you confirm the `client certificate` has been added to postman? 

The `client certificate` can be found [here](https://github.com/ConsumerDataRight/mock-register/blob/main/CertificateManagement/mtls/client.pfx). The steps required to add the `client certificate` to postman can be found [here](https://github.com/ConsumerDataRight/mock-register/blob/main/Postman/README.md).

I was unable to replicate the issue using the latest postman collection and client certificate from main and the latest container from docker hub.

I did run in to another issue when executing the `Admin API - Load Metadata`:

Two `abn` fields and two `acn` fields in the body of the `Admin API - Load Metadata` postman request were being truncated and the database command would throw an error.

The database migrations create `abn` as varchar(11). Reduce the length of these `abn` values to be less than or equal to 11 to work around this issue.
- 98765456788765
- 123981224123

The database migrations create `acn` as varchar(9). Reduce the length of these `acn` values to be less than or equal to 9 to work around this issue.
- 1121231231
- 1223412123

The `abn` and `acn` fields are not validated beyond the length of the text. Any text can go into the field as long as it is not too long.

An issue has been added to our backlog and will be included in our next mock-register release to GitHub and Docker Hub.

**Comment by CDR-AndrewG** [comment]
Hi @aka4rKO,

The issue listed above regarding `abn` and `acn` field lengths throwing an error has been resolved in our latest release.

Let me know if you are still encountering an issue.

**Comment by CDR-AndrewG** [comment]
Hi @aka4rKO,

Please reach out if you are having any other issues.
