### ISSUE TITLE
Can't get Token for Other Scopes

### ISSUE THREAD

**Issue by AngusB-SA** [ConsumerDataRight/mock-register#71]
**Describe the bug**
When running the `mock-register` in docker, the login endpoint provided with the Postman collection only allows login to `cdr-register:read` scope, while Admin Metadata load shows that the given login should be able to access any scope in the mock environment.

The error appears as a HTTP `400` response with the content `"error": "invalid_client"`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the `mock-register` in Docker.
2. Open the `/idp/connect/token` endpoint available in the postman collection.
3. Change the scope argument in the body to another available option, like `common:customer.basic:read`.
4. Make the call to the endpoint.
5. See an error response as above, with content `"error": "invalid_client"`.

**Expected behaviour**
The expectation would be that the endpoint would return a valid token for the alternate scope.

**Comment by CDR-AndrewG** [comment]
Hi @AngusB-SA,

Thank you for raising this issue.

For authenticated endpoints provided by the `mock-register`, only `cdr-register:bank:read` and `cdr-register:read` are considered as valid scopes. The `token` endpoint can be called without the scope argument provided. The token in the response will default to use `cdr-register:read` when no scope is provided. 

The other scopes visible in the `Admin API - Get Metadata` response are used exclusively for Data Recipient - Software Product to Data Holder authorisation and authentication. 

More information for CDR Data scopes can be seen [here](https://consumerdatastandardsaustralia.github.io/standards/#cdr-data).
More information for Register scopes can be seen [here](https://consumerdatastandardsaustralia.github.io/standards/#admin-amp-registration).
