### ISSUE TITLE
Mock registry is giving certificate mismatch error while calling IDP token 

### ISSUE THREAD

**Issue by l-sateesh** [ConsumerDataRight/mock-register#79]
URGENT////
**For testing we have upgraded our internal mock registry to the latest CDR mock register version 1.1.1.  We have encountered an error at IDP token endpoint around client certification validation failure. Internally we have checked mock client and server certificates as part of investigation. 
Hoping to get your help to assess if the error we are encountering is resulting from last week's mock register changes and if you have seen similar issues logged by other participants. 
**

**To Reproduce**
1. Go to "Client assertion" for assertion ID - successful
2. Call /IDP/connect/token using assertion ID - giving certification validation error " Client certification validation failed"

{

    "error": "invalid_client",

    "error_description": "Client certificate validation failed"

}
https://github.com/ConsumerDataRight/mock-register/blob/main/Source/CDR.Register.Infosec/Controllers/TokenController.cs
[Error screenshot.docx](https://github.com/ConsumerDataRight/mock-register/files/11106588/Error.screenshot.docx)

**Expected behaviour**
valid IDP token 

**Screenshots**
attached

**Additional context**

**Comment by CDR-AndrewG** [comment]
Hi @l-sateesh,

Thank you for contacting us and raising this issue.

Can you have a look at the underlying SQL base for the register? What the issue could be is that the client certificate you are using cannot be found in the `dbo.SoftwareProductCertificate` table.

This certificate validation that is failing:

For the given `SoftwareProductId`, check that the client certificate provided has a matching `CommonName` and `Thumbprint` in the `dbo.SoftwareProductCertificate` table.

**Comment by l-sateesh** [comment]
Thanks, Andrew, for the quick turnaround.  We are checking this now and will come back with the update.

Regards

Lalita

**Comment by l-sateesh** [comment]
Hi , we have followed the mentioned steps aaand facing the same error. Any other trouble shooting methods?

Regards

**Comment by CDR-AndrewG** [comment]
Hi @l-sateesh,

Another item to check is that the mtls client certificate configured in postman matches up with the certificate record in the database. The client_id used in the postman request must also match the certificate record in the database. 
As long as the following matches then the error being experienced should stop occurring.

Postman `client_Id` matches the Register `SoftwareProductId`
Postman `client certificate` has a corresponding record for that `client_Id` in the `dbo.SoftwareProductCertificate` table

**Comment by l-sateesh** [comment]
Hi 

We have tried the above however still encountering the same error. If there is an opportunity to get on a call that would be great. Thanks

**Comment by CDR-AndrewG** [comment]
Hi @l-sateesh,

Please try this also.

After receiving the error message, can you have a look at the latest records in the database log table `dbo.LogEvents-Infosec`? There should be some records in the log table for the error or some other information that might provide some clues.

**Comment by l-sateesh** [comment]
Hi  ,
We are still testing and will update. Thanks

**Comment by l-sateesh** [comment]
Hi ,
We are facing the same problem and hence hoping if we could get on a quick call to try and resolve this issue. Thanks

**Comment by l-sateesh** [comment]
Hi, Let me know if we can get on a call to discuss this issue.  As we have looked into all the steps and are still encountering the same issue. thanks

**Comment by CDR-AndrewG** [comment]
Hi @l-sateesh,

Unfortunately, we do not have an on-call function or helpdesk for managing issues experienced when using these repos.

Were there any errors in the log table, `dbo.LogEvents-Infosec`? Are you able to send the top 1000 records of the log table directly after this error occurs?

**Comment by l-sateesh** [comment]
Thanks, have reached out to the team to get the log details.

**Comment by l-sateesh** [comment]
Hi Team, we were able to find a resolution on Friday evening and it's working fine now. Thanks for your support to help resolve the issue and appreciate the quick turnaround with this request. thanks

**Comment by CDR-AndrewG** [comment]
Hi @l-sateesh,

That is great to hear. Please reach out again in the future if any other issues arise.
