### ISSUE TITLE
ssa jwks uri not aligning with the doc

### ISSUE THREAD

**Issue by Smoovsky** [ConsumerDataRight/mock-register#80]
According to the doc [Get Jwks](https://consumerdatastandardsaustralia.github.io/standards/#get-jwks), the ssa jwks uri should be ```https://<tls_base_uri>/jwk``` but the actual ssa jwks uri in the mock register is ```https://<tls_base_uri>/cdr-register/v1/jwks```

After consulting [#516](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/516), ```https://<tls_base_uri>/jwk``` should currently be the correct uri, but it seems there is some hesitation with regard to whether this uri should follow the [Base Uri](https://consumerdatastandardsaustralia.github.io/standards/#uri-structure) convention.

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky.

Thank you for reaching out and logging this issue.

The mock-register jwks uri has been setup to closely match the production CDR Register. One of our design philosophies for the mock-register is to treat the production CDR Register as the source of truth. We believe giving a consistent experience to users of the mock-register and the production CDR Register will benefit those who use both.

As the production CDR Register uses https://api.cdr.gov.au/cdr-register/v1/jwks, we have opted to use https://localhost:7000/cdr-register/v1/jwks for the mock-register.

There are two open change requests logged to update the Consumer Data Standards to list the actual CDR Register jwks. [516](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/516), [552](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/552)
